name: Test

on: [pull_request]

jobs:
  go-mod-tidy:
    name: "Go mod tidy"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Tidy check
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/magefile/mage
          mage gomodtidy
